googlemaps/google-maps-services-js

- lib/index.js
- lib/internal/make-api-call.js
- spec/unit/index-spec.js
> Add channel parameter to URL

- lib/apis/places.js
- lib/apis/roads.js
- lib/index.js
- spec/e2e/places-spec.js
- spec/e2e/roads-spec.js
Mostly adds some missing APIs:
- nearest roads
- places radar search
- places nearby search
Also replaces deprecated `types` param with `type` param for places APIs (see https://developers.google.com/places/web-service/search).
@stephenfarrar PTAL
> Missing apis

- lib/apis/places.js
- lib/index.js
- spec/e2e/places-spec.js
> Add query autocomplete and fix places auto complete. Closes #44.

- lib/internal/validate.js
> Fix InvalidValueError to include the message in the stack trace.

- lib/internal/make-url-request.js
> Catch JSON.parse errors.

- lib/apis/places.js
- lib/internal/validate.js
placesPhoto should throw error if neither maxwidth or maxheight is declared
> placesPhoto should throw error if neither maxwidth or maxheigh is declared

- lib/apis/places.js
- spec/e2e/places-spec.js
test failure is related to rate limiting
> add support for subfields in mask for places

- .travis.yml
- package.json
> automatically deploy tagged releases to npm

- .travis.yml
- package.json
- spec/e2e/places-spec.js
> run e2e and unit tests together and simplify check of e2e response

- CHANGELOG.md
- lib/apis/places.js
- lib/internal/validate.js
- spec/unit/validate-spec.js
Adds a deprecation warning to `alt_id`, `id`, `reference` and `scope`.
> add deprecation_warning

- samples/directions-api.js
- samples/distance-matrix-api.js
- samples/elevation-api.js
- samples/geocoding-api.js
- samples/places-api.js
- samples/roads-api.js
- samples/time-zone-api.js
Concerning  the issue  here [Update documentation](https://github.com/googlemaps/google-maps-services-js/issues/143#issue-287801615) , I created some sample snippets on how to use the API.
> add samples

- lib/index.js
- lib/internal/make-api-call.js
- spec/e2e/geocode-spec.js
- spec/unit/index-spec.js
pulled the e2e failures into #305 
Note: this library still has issues in nondeterministic tests or bugs for throttling. Also some formatting noise slipped through.
> feat: support experience id

- e2e/places/details.test.ts
- e2e/places/findplacefromtext.test.ts
- src/places/details.test.ts
- src/places/details.ts
- src/places/findplacefromtext.test.ts
- src/places/findplacefromtext.ts
closes #314 
Lucky there is only one array format for this request...
> fix: use comma arrayFormat for place fields

- package-lock.json
- package.json
This should add a release in addition to the tag.
> build: use semantic-release github plugin

- README.md
> docs(README): improve readme with migration guide

- src/places/autocomplete.ts
> fix: make autocomplete sessiontoken optional

- package-lock.json
- package.json
> fix: replace fork of query-string

- src/client.test.ts
- src/client.ts
> feat: support passing custom AxiosInstance to client

- e2e/places/queryautocomplete.test.ts
- src/places/queryautocomplete.ts
> fix: queryautocomplete response is now correct

- README.md
Adds a link to the discord server.
> docs(README): add discord link and badge

- src/common.ts
> fix: typo of `PlacePhoto::photo_reference`

- e2e/geocode/reversegeocode.test.ts
> test: add e2e reversegeocode test with place_id

- src/client.ts
Fixes #<issue_number_goes_here> 🦕
> fix: make ClientOptions optional in Client constructor

- .travis.yml
- package.json
> test: limit e2e tests on forks

- e2e/elevation.test.ts
- src/elevation.test.ts
- src/elevation.ts
> feat: add support for elevation along path

- .github/workflows/docs.yml
- .gitignore
- README.md
- package-lock.json
- package.json
- typedoc.js
> docs: add documentation with typedoc

- package-lock.json
- package.json
- src/client.ts
This adds retry-axios to the client in all cases except when an axiosInstance is passed to the constructor.
closes #326
> feat: add retry-axios as default

- src/index.ts
> fix: export types at root

- e2e/timezone.test.ts
- src/directions.ts
- src/distance.ts
- src/serialize.test.ts
- src/serialize.ts
- src/timezone.test.ts
- src/timezone.ts
> fix: handle date objects correctly in serializer

- src/places/placesnearby.ts
> fix: set radius optional on PlacesNearbyRequest

- e2e/client.test.ts
> test: add test for readme usage

- e2e/compression.test.ts
- e2e/directions.test.ts
- e2e/geolocation.test.ts
- e2e/places/findplacefromtext.test.ts
- e2e/timezone.test.ts
- src/common.ts
- src/geocode/reversegeocode.ts
- src/geolocate.ts
- src/places/autocomplete.ts
- src/places/details.ts
- src/places/placesnearby.test.ts
- src/places/placesnearby.ts
This make the various types available at runtime.
> feat: use enums everywhere

- e2e/directions.test.ts
- src/common.ts
> fix: steps polyline is object not string

- src/common.ts
> fix: add additional AddressTypes

- e2e/directions.test.ts
- src/directions.ts
> fix: use correct handling of optimize

- README.md
- e2e/client.test.ts
> fix: include correct code for readme

- .github/workflows/ci.yml
- src/adapter.test.ts
> test: nock cleanup

- README.md
> docs: update example without switch on status

- src/geocode/geocode.ts
Add place_id param to GeocodeRequest.
Fixes #408  🦕
> feat: add place_id to geocode

- package-lock.json
- package.json
This should avoid hiding the underlying exception.
close #403 
close #380
> fix: use updated retry-axios version

- src/index.ts
> fix: export PlaceAutocompleteType from main module

- e2e/distance.test.ts
> test: add distance test

- e2e/directions.test.ts
- src/serialize.test.ts
- src/serialize.ts
> fix: support serializing now

- src/serialize.test.ts
- src/serialize.ts
> fix: do not mutate params in serializer

- README.md
> docs: remove unused import in quickstart

- src/places/autocomplete.ts
Thank you for opening a Pull Request!
---
Fixes #471  🦕
> fix: add missing origin request parameter for Places Autocomplete

- e2e/places/details.test.ts
- package-lock.json
- package.json
- src/common.ts
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕
> fix: add missing place result properties

- package-lock.json
- package.json
- tsconfig.json
> fix: skip axios 0.20.0 and rm default ts libs

- package-lock.json
- package.json
- typedoc.js
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes #<issue_number_goes_here> 🦕
> build: update typedoc settings

- package-lock.json
- package.json
closes #482 with new version of axios
> build(deps): update axios

- src/common.ts
Thank you for opening a Pull Request!
---
Fixes #543  🦕
> fix(definition): duration_in_traffic route leg property is optional

- README.md
> docs(README): fix typo in readme

- e2e/places/autocomplete.test.ts
- e2e/places/details.test.ts
- e2e/places/findplacefromtext.test.ts
- e2e/places/placesnearby.test.ts
- e2e/places/queryautocomplete.test.ts
- e2e/places/textsearch.test.ts
> fix: add fields param

- package-lock.json
- package.json
These are included as part of the GitHub workflow.
> build: remove release dev-deps

- src/common.ts
> fix: directions step travel mode

- .github/workflows/release.yml
- .releaserc
- package.json
- including semantic-release-interval
- patching on docs(README)
- including more in release notes
> build: update semantic release config

- src/client.ts
- src/common.ts
- src/index.ts
This should also fix items missing from docs.
> fix: export additional stypes at top

- src/client.ts
Example for `Client.geocode()`
---
cc #454 🦕
> docs: add geocode example #454

- package-lock.json
- package.json
- yarn.lock
reverts axios and retry-axios deps - upgrading broke jest tests.
> fix: revert axios deps

- package-lock.json
- package.json
- yarn.lock
Downgrades versions for axios and query-string and sets fixed versions.
> fix: revert dep versions

- e2e/places/autocomplete.test.ts
- e2e/places/details.test.ts
- e2e/places/placesnearby.test.ts
- e2e/places/queryautocomplete.test.ts
- e2e/places/textsearch.test.ts
- jest.config.js
- package-lock.json
- package.json
- src/adapter.test.ts
- src/adapter.ts
- src/serialize.ts
- tsconfig.json
- yarn.lock
Update all dependencies to their latest versions and refactor some code to work with the new major versions.
> chore: update all dependencies

- e2e/geocode/reversegeocode.test.ts
- package-lock.json
- package.json
- src/common.ts
- src/geocode/reversegeocode.test.ts
- src/geocode/reversegeocode.ts
- src/serialize.ts
- yarn.lock
Thank you for opening a Pull Request!
---
- [X ] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ X] Ensure the tests and linter pass
- [X ] Code coverage does not decrease (if any source code was changed)
- [ X] Appropriate docs were updated (if necessary)
Fixes #1188 🦕
> feat: Added Address Descriptors to Geocoding response.

- README.md
Thank you for opening a Pull Request!
---
Fixes #1300 🦕
> bug: removing $ for the npm install command
