lib/internal/make-url-request.js
I had been getting a fatal "socket hang up" error occasionally while using this module which was killing my app. Some [research](http://stackoverflow.com/a/21957469/3187556) showed that you need to listen for errors on the `ClientRequest` object and not just the `ServerResponse`. This pull request implements that fix. I have signed the CLA.
=> Fix "socket hang up" error

lib/internal/convert.js
Resolves issue #38. Currently if a Unix timestamp (seconds since epoch) is passed to the `timeStamp` conversion method it will be divided by 1000. This should only happen to values from Javascript's `Date.getTime()`, which returns milliseconds since epoch.
=> Fix timestamp conversion to accept Unix time

lib/internal/attempt.js, lib/internal/make-api-call.js, lib/internal/task.js, lib/internal/throttled-queue.js, lib/internal/wait.js, spec/mock-clock.js, spec/unit/attempt-spec.js, spec/unit/index-spec.js, spec/unit/task-spec.js, spec/unit/throttled-queue-spec.js
Timers are used in several places:
* request timeout
* throttled queue
* retry with exponential back-off
This change makes cancelling properly stop the timers.
=> Properly cancel timers

lib/apis/places.js, spec/e2e/places-spec.js
Changed ‘rankBy’ parameter to ‘rankby’. Using ‘rankBy’ always returns zero results.
Added test case for nearby places search ranked by distance.
Documentation at https://developers.google.com/maps/documentation/javascript/places should also be updated. Already submitted feedback.
=> Fix placesNearby rankby parameter

lib/apis/places.js
I filed issue https://github.com/googlemaps/google-maps-services-js/issues/46 but decided to just make a PR.
Looks like the code was updated  in https://github.com/googlemaps/google-maps-services-js/commit/1d55956ecfc8132de2a9528127323b8d15088ca6 but documentation wasn't.
=> Updated query.type doc for autocomplete in places.js

lib/apis/directions.js, lib/apis/distance-matrix.js, lib/apis/elevation.js, lib/apis/geocode.js, lib/apis/places.js, lib/apis/roads.js, lib/apis/timezone.js
See https://googlemaps.github.io/google-maps-services-js/docs/global.html#utils
=> Prevent the licenses turning up in the generated jsdoc.

docs/interfaces.js, lib/internal/make-api-call.js, lib/internal/make-url-request.js, lib/internal/task.js, spec/unit/index-spec.js
Note: this is a breaking change to the library.
Fixes #32
=> Treat unsuccessful API responses as errors

lib/internal/task.js
=> Remove memory leak in Task.

lib/internal/make-url-request.js
Current response time is around 1000ms, because it creates a new socket and close it for every single request. This is too slow for some applications.
I added 1 single line, to use keep-alive, and this cuts the time down to ~250ms.
=> speed up response by 4x fold

lib/internal/make-url-request.js
Hi!
I see an issue with wrong HTTPS response chunks concatenation with multibyte strings in this code:
`
var data = '';
response.on('data', function(chunk) {
data += chunk;
});
`
Please consider to review my pull request, fixing this issue.
=> Fixed handling multibyte encoding responses

lib/internal/make-url-request.js
The commit before sets `https.globalAgent.keepAlive = true`, which was very dangerous, because this dirties other modules that rely on `https` module. For instance, it messes up some of Stripe's consecutive requests.
This commits give google map its own local agent (request pool), thus no conflicts with other modules.
=> Use local https agent, instead of dirtying global agent

docs/HOME.md
In reference to #89 
I left the syntax in the example for promises very simple. The `asPromise()` could arguably be on the next line, like the following:
```js
googleMapsClient.geocode({address: '1600 Amphitheatre Parkway, Mountain View, CA'})
.asPromise()
.then((response) => {
console.log(response.json.results);
})
.catch((err) => {
console.log(err);
});
```
But, I wanted people to see that it is chained onto the `googleMapsClient` directly and thought the code in the actual PR was more clear.
I also noticed that the second code example in the docs does not have the `js` declaration within the markdown to highlight it is javascript. "```js" would syntax highlight the following
```js
// Geocode an address.
googleMapsClient.geocode({
address: '1600 Amphitheatre Parkway, Mountain View, CA' …
=> Update docs on proper usage of `asPromise()`

lib/internal/make-api-call.js
As mentioned in #88 I wanted a way to return all the settings and data that is used to query a particular API, for debugging these calls. Although the solution in the mention issues works, I think it's not perfect. When I just copy the `makeUrlRequest` code and change it for my project I don't get any bug fixes or new features from the module in this library. So I thought I try to figure out how everyone would win.
I updated the `makeApiCall` method to return not only the response from a particular API but also the values that were given to that API.
Hope that would fit into the lib which we use quite often now.
=> Add input data to output data.

lib/internal/validate.js
@stephenfarrar PTAL
This changes boolean validation to only return its value when true - all of the bool params in the APIs default to false, and several of them (all the ones I checked) treat the presence of any value as true, so when false we want to drop it entirely.
For this change to work I also made a change which I think is a bugfix but wanted you to triple-check for me, the line `if (key in object && valid !== undefined) {`
=> Exclude false values from params

docs/HOME.md
Addresses #99 
I opted not to use ES6 shorthand here, as I think it's nicer to make clear that the property name is 'Promise'.
If it's not clear enough, I'm happy to also add an example of using Bluebird or another Promise library.
=> Added example of promise constructor

lib/apis/geocode.js
`bounds` parameter structure was modified by 8c51daba69c43c8b2aac547e1fb7ad84d70db047.  
Issue #78 was possibly caused by this discrepancy.
*It is also unclear why bounds parameter structure was changed at all when adding those tests. google-maps-services libraries for other languages still use an interface with `southwest` and `northeast`.*
=> Fix JSDoc for geocode bounds parameter

CONTRIBUTING.md
Whitespace between the closing brackets and opening parenthesis of markdown links prevented github from rendering the links.
=> Fixing errors in Github-flavored markdown

lib/apis/places.js
With this change client.places() can accept the region parameter.
=> Add region parameter to Text Search API

lib/apis/places.js
Session token is nullable in Autocomplete
https://developers.google.com/maps/documentation/javascript/places-autocomplete#session_tokens
=> Session token should be optional in AutoComplete

lib/internal/make-url-request.js, package.json
Implemented https-proxy-agent library that connects to an intermediary "proxy" server and issues the CONNECT HTTP method, which tells the proxy to open a direct TCP connection to the destination server. This will help us to get the google maps client api to work from behind the corporate proxies.
=> added https proxy agent for pursuing the requests behind corporate proxy

lib/internal/make-api-call.js, spec/e2e/places-spec.js
When a next_page_token is returned for nearby places searches,  an INVALID_REQUEST status is returned if the token is sent too quickly. This fixes retry logic for this case, and reenables a pagination test that  was  previously failing  because of this.
=> fixes pagination INVALID_REQUEST handling

README.md
Adds a README npm badge so that users can go directly to npm.
[![npm](https://img.shields.io/npm/v/@google/maps.svg)](https://www.npmjs.com/package/@google/maps)
=> docs: Add npm badge

lib/apis/places.js
Without passing the `origin` parameter to the `placesAutoComplete()` function we can't get the distance of the result items from our specified location. 
(`result.json.predictions[n]distance_meters` in the response).
=> Add the "origin" parameter to the placesAutoComplete function

lib/index.js
I've had the same problem as https://github.com/googlemaps/google-maps-services-js/issues/196 in which a quota-exceeded failure wouldn't bubble up to my callback and I would have to wait for the whole timeout before getting a response. Also, setting a short timeout isn't an interesting option as the initial error would not bubble up either. The best thing to do would be to override `canRetry`  and setting it to a function that returns false in order to bypass the retry mechanism and receive an error. This is the behavior I wanted.
I noticed that the `customParams` object was passed second instead of first, so anything put in there would be overwritten by the default params.
This fixes it and allows customParams to overwrite default params.
=> Allow custom parameters to override defaults

spec/e2e/distance-matrix-spec.js
departure time changed from miliseconds to seconds
=> distance matrix departure time unit change from miliseconds to seconds

lib/internal/make-url-request.js
Hi!
In a test environment, I am mocking google maps HTTP request and returns results for directions API requests.
In my responses, I return the header of `Content-Type` with `utf-8` lowercase and I can't change since it's hardcoded in the framework (express).
This PR changes the comparison not to be case-sensitive.
=> Check content-type without significance of case-sensitivity

lib/apis/places.js
Fixes misspelling in field name validation - it must be `reviews`, not `review`: https://developers.google.com/places/web-service/place-data-fields
=> [BUG] fix `reviews` field name

.gitignore, package.json
=> run e2e tests separately

spec/e2e/geocode-spec.js
This style of test is not worth the hassle and if we want to run regression tests based upon API call results we should do it elsewhere.
=> tests: remove data checks

src/common.ts
This is a common response type. In my case I was writing the following:
```
const gmapsResult = await googleMapsClient.placeQueryAutocomplete({
params: {
input: keyphrase,
key: process.env.GOOGLE_MAPS_API_KEY,
},
});
if (gmapsResult.data.status === "ZERO_RESULTS") { // TypeScript error.
}
```
when the actual response from the API was in fact the "ZERO_RESULTS" response as documented at https://developers.google.com/places/web-service/query#query_autocomplete_status_codes
In the interim I worked around the TypeScript error by coercing the status to string and then comparing.
=> fix: Support a Status of ZERO_RESULTS

e2e/compression.test.ts, src/client.test.ts, src/client.ts
Adds an "Accept-Encoding: gzip" header to all requests to improve
transfer speed and bandwidth utilization via server response
compression.
Most (all?) of the Maps APIs support serving compressed content and
this library's HTTP client (Axios) will transparently handle
decompression.
Requesting compressed content is already the default behavior of the Go
and Java google-maps-services client libraries.
A user can opt-out of compression by specifying a custom
Accept-Encoding ("identity") via config.headers at Client instantiation
or by instantiating a Client with an Axios client.
Fixes #356
=> feat: Request gzip response compression by default

src/index.ts
This should make it easier to use the enums.
=> fix: export common at root

src/common.ts
Add business_status to Place responses to better differentiate between temporary and permanent closures.
=> feat: add business_status

src/common.ts
Fixes #404 
According to the documentation [here](https://developers.google.com/places/web-service/details#PlaceDetailsStatusCodes), the status `NOT_FOUND` is a valid response the API might return.
Added it to the `Status` enum.
=> fix: Add NOT_FOUND to the status enum according to documentation

src/common.ts
`permanently_closed` is deprecated in favor of `business_status`
=> docs: add note stating permanently_closed is deprecated

e2e/client.test.ts, package-lock.json, package.json, src/adapter.test.ts, src/adapter.ts, src/client.ts
close #393 
BREAKING CHANGE: responses that previously returned a 200 with a non OK status and resolved will now reject with something other than 200.
From a test case:
```js
await client
.elevation({
params: {
locations: [{ lat: 45, lng: -110 }],
key: "invalid key",
},
timeout: 1000, // milliseconds
})
.catch((e: AxiosError) => {
expect(e.response.status).toEqual(403);
expect(e.response.data.status).toEqual(Status.REQUEST_DENIED);
});
});
```
=> fix!: use custom http adapter to set status code and reject

src/index.ts
=> fix: export PlaceAutocompleteResult

README.md
This PR fixes a typo in the README.
=> docs: fix spelling documenation -> documentation

src/common.ts
Fixes #402, #573
Note that `ward` was removed as it does not appear on https://developers.google.com/maps/documentation/places/web-service/supported_types
Previous comments on AddressType members were moved to their corresponding members on the place types.
=> fix: Updated place types and changed AddressType to use place types

README.md, src/common.ts, src/directions.test.ts, src/directions.ts, src/distance.test.ts, src/distance.ts, src/elevation.test.ts, src/elevation.ts, src/geocode/geocode.ts, src/geocode/reversegeocode.ts, src/places/autocomplete.ts, src/places/details.ts, src/places/findplacefromtext.ts, src/places/placesnearby.ts, src/places/queryautocomplete.ts, src/places/textsearch.ts, src/roads/nearestroads.test.ts, src/roads/nearestroads.ts, src/roads/snaptoroads.test.ts, src/roads/snaptoroads.ts, src/serialize.test.ts, src/serialize.ts, src/timezone.ts
Fixes #639
I have not updated the tests, changelog, or version yet. I wanted to get feedback on the overall approach first.
The approach that I've taken is adding a special case in the `serializer` method that checks the params passed in. If `client_id` and `client_secret` are present it'll do the appropriate encoding and attachment/removal of query params.
Because the current implementation just passes all given parameters straight through to Axios this seemed like the most straightforward place to put this logic. Since this is common logic it felt appropriate to try and keep it in a common layer rather than needing to add any special logic (or defining explicit serializer params) per function. …
=> feat: add client_id and client_secret auth alternatives

e2e/places/details.test.ts, e2e/places/placesnearby.test.ts, e2e/places/textsearch.test.ts, src/common.ts
Changes in https://developers.google.com/maps/documentation/places/web-service/icons, but that page has a typo where url should be uri. (Fixing that too!)
=> fix: add new icon fields

package-lock.json, package.json
=> fix: add crypto to deps

.github/workflows/ci.yml
Only use codecov on unit tests, not e2e since these run for a subset of contributors.
=> build: ignore e2e in codecov

package-lock.json, package.json, tsconfig.json
closes #702 using fix in https://github.com/googlemaps/js-url-signature/pull/28
kind of a mess in TS: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34960
=> fix: use new version of @googlemaps/url-signature

package-lock.json
url-signature-1.0.24 fixes an issue with source maps not being published.
---
Fixes #767
=> bump @googlemaps/url-signature from 1.0.21 to 1.0.24

src/common.ts
I noticed that `PlaceType1` does not contain all place types listed on the official documentation: https://developers.google.com/maps/documentation/places/web-service/supported_types#table1
This change adds the missing types `drugstore`, `light_rail_station` & `university`.
=> Update `PlaceType1` to match official documentation

package.json
there's a Jest-related issue that is causing e2e tests to fail. Disabling temporarily so we can cut a release with the fixed axios deps.
=> fix: temporarily disabline e2e tests

src/client.ts
This PR removes an extra `)` in one of the comments for geocoding. It was showing up in the auto-generated documentation.
Picture of what the wrong documentation looks like:
What it will look like after this PR gets merged:
---
=> fix: remove extra parenthesis from documentation example

package-lock.json, package.json, yarn.lock
Current master breaks since this still is a commonJS package and as such can't require ESM packages like query-string v8+ and retry-axios v3+.
To update those dependencies we need to make a major-release where we switch to ESM-only as well.
=> fix: only use pre-ESM dependencies

e2e/places/photo.test.ts, jest.config.js, package.json
This should fix the failing tests observed in recent workflow-runs. 
The test for the Place Photos API was using a hardcoded `photoreference` which apparently is no longer valid. 
The updated test retrieves a photo reference via place details request, which should always produce valid results.
Also changed the way the tests are run. This includes specifying `--runInBand` via command line (avoid problems with serializing error-objects with cyclic structure) and only using `--collectCoverage` when running tests via npm when it's actually required.
=> test: fix places/photo test
